language: python
python:
  - 2.7
  - 3.3
  - 3.4
script: make test
cache:
  - apt
  - pip
install:
  - sudo apt-get -y install libatlas-base-dev libatlas-dev lib{blas,lapack}-dev
  # some conda magic to install numpy, scipy
  # see http://sburns.org/2014/03/28/faster-travis-builds.html
  - sudo pip install conda==4.3.2
  - conda_deps='pip numpy scipy matplotlib cython scikit-learn'
  - conda create -p $HOME/py --yes $conda_deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - pip install -r requirements.txt
  - python setup.py build_ext --inplace
